spring.application.name=server-audio

server.port=${SERVER_PORT:8080}

server-main.url=${SERVER_MAIN_URL}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=server-group
spring.kafka.consumer.auto-offset-reset=earliest